// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPTytyDtCUqgK_k1hDYLUY3p6J8fJVx_w',
    appId: '1:725184092543:web:941e1d84f1dd894918e24a',
    messagingSenderId: '725184092543',
    projectId: 'filosign-8bf18',
    authDomain: 'filosign-8bf18.firebaseapp.com',
    storageBucket: 'filosign-8bf18.firebasestorage.app',
    measurementId: 'G-PN08CZGK03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbY7Cn9LZvHwY0J68DU6WuS2cQZynsfwM',
    appId: '1:725184092543:android:74a3b752f3920d6718e24a',
    messagingSenderId: '725184092543',
    projectId: 'filosign-8bf18',
    storageBucket: 'filosign-8bf18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxVO2fsFOuVCBDB2eh9_S5O0loLTBrkwU',
    appId: '1:725184092543:ios:e302753d720259a718e24a',
    messagingSenderId: '725184092543',
    projectId: 'filosign-8bf18',
    storageBucket: 'filosign-8bf18.firebasestorage.app',
    iosBundleId: 'com.example.filosign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxVO2fsFOuVCBDB2eh9_S5O0loLTBrkwU',
    appId: '1:725184092543:ios:e302753d720259a718e24a',
    messagingSenderId: '725184092543',
    projectId: 'filosign-8bf18',
    storageBucket: 'filosign-8bf18.firebasestorage.app',
    iosBundleId: 'com.example.filosign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPTytyDtCUqgK_k1hDYLUY3p6J8fJVx_w',
    appId: '1:725184092543:web:7a0f1fb9e41da7b118e24a',
    messagingSenderId: '725184092543',
    projectId: 'filosign-8bf18',
    authDomain: 'filosign-8bf18.firebaseapp.com',
    storageBucket: 'filosign-8bf18.firebasestorage.app',
    measurementId: 'G-H0Z34CWP0K',
  );
}
